name: build
on: [push]
jobs:
  build:
    name: Build on Push
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Download golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.21.0
    - name: Download modules
      run: make download
    - name: CI
      run: make ci
    - name: Build
      run: make build
